### ISSUE TITLE
can't open your dataset link

### ISSUE THREAD

**Issue by yanghu819** [fabbrimatteo/LoCO#11]
From china, could you please give the google data link? thank you !

**Comment by fabbrimatteo** [comment]
Hi @kickingass,
To obtain the dataset, please follow the instructions [here](https://github.com/fabbrimatteo/JTA-Dataset#obtain-the-dataset).

**Comment by yanghu819** [comment]
thanks


Matteo Fabbri <notifications@github.com> 于2020年9月25日周五 下午5:41写道：
