### ISSUE TITLE
Could you please give more guide for running with human3.6 dataset？ 

### ISSUE THREAD

**Issue by yanghu819** [fabbrimatteo/LoCO#12]
Human 3.6m is more accessable for me, thank you very much for reviewing my issue!

**Comment by fabbrimatteo** [comment]
Hi @kickingass,
I am sorry, but I don't plan to add the code for Human3.6m soon. I am too busy at the moment. Hope you understand!

**Comment by yanghu819** [comment]
ok，I see

Matteo Fabbri <notifications@github.com> 于2020年9月28日周一 下午6:33写道：
