### ISSUE TITLE
Facing "ModuleNotFoundError: No module named "vtkCommonCorePython" error while running demo.py

### ISSUE THREAD

**Issue by shubhamkvpl** [fabbrimatteo/LoCO#13]
Hello,

I am trying to run this code but facing the error "ModuleNotFoundError: No module named "vtkCommonCorePython" while running the demo.py file. The file"vtkCommonCorePython" already present in the "vtkmodules" folder. I also added the "vtkmodules" path to the environment variable as suggested by the stackoverflow link "https://stackoverflow.com/questions/13495285/importerror-no-module-named-vtkcommonpython". Still, the issue is unresolvable. Could you please tell me the which version of "vtk" you have used in the code.

Thanks,
Shubham Gupta

**Comment by fabbrimatteo** [comment]
Hi @shubhamkvpl,

I am using the 8.1.2 vtk version.
