### ISSUE TITLE
get the dataset and  code of the GT?

### ISSUE THREAD

**Issue by ZXin0305** [fabbrimatteo/LoCO#17]
hi,I want to train the model while I do not have the dataset,so could you tell me how can I get it?
And,I don't know what's the formulation meaning:
    k = (-1) * np.sqrt(
        fx ** 2 * fy ** 2 + fx ** 2 * cy ** 2 - 2 * fx ** 2 * cy * y2d + fx ** 2 * y2d ** 2 +
        fy ** 2 * cx ** 2 - 2 * fy ** 2 * cx * x2d + fy ** 2 * x2d ** 2
    )

    x3d = ((fy * cam_dist * cx) - (fy * cam_dist * x2d)) / k
    y3d = ((fx * cy * cam_dist) - (fx * cam_dist * y2d)) / k
    z3d = -(fx * fy * cam_dist) / k

    return x3d, y3d, z3d

I know it is to get the 3D coordinate in the camera coordinate system,but I can't understand it..Maybe you can give me some suggest 
Thank you very much !!!!!

**Comment by fabbrimatteo** [comment]
To download JTA, please follow the instructions reported [here](https://github.com/fabbrimatteo/JTA-Dataset#obtain-the-dataset).

You can find additional details on the formulation in [this](https://github.com/fabbrimatteo/LoCO/issues/4#issuecomment-648126174) issue.
