### ISSUE TITLE
download the dataset

### ISSUE THREAD

**Issue by ZXin0305** [fabbrimatteo/LoCO#18]
Hello,it's very glad for you to  watch this email.I'm Zhang Xin,a first-year graduate student at Zhejiang University of Technology in Zhejiang Province, China.These days I read the paper "Compressed Volumetric Heatmaps for Multi-Person 3D Pose Estimation" and I want to train the model by myself while I don't have the dataset.

With this email we declare that we will use the JTA Dataset for research and educational purposes only, since we are aware that commercial use is prohibited. We also undertake to purchase a copy of Grand Theft Auto V.

（But I don’t think I have extra money to buy this game，because I'm poor......Maybe my English is not very good,thank you ~）
and my email is 2498932306@qq.com or zx@2498932306.net

**Comment by fabbrimatteo** [comment]
Please, to request the JTA dataset, send an email to the email address specified [here](https://github.com/fabbrimatteo/JTA-Dataset#obtain-the-dataset)
