### ISSUE TITLE
the cpp file

### ISSUE THREAD

**Issue by ZXin0305** [fabbrimatteo/LoCO#19]
hello ,I want to ask that how can I import the 'nms3d_cuda' sucessfully?

**Comment by fabbrimatteo** [comment]
Hi,
Please, follow the instructions reported [here](https://github.com/fabbrimatteo/LoCO#compile-cuda-kernel).

**Comment by ZXin0305** [comment]
Okey,thank you very very much!!! And I'm sorry for that  I didn’t see your reply in time! Finally, I think your code style is very good!
