### ISSUE TITLE
How to train VHA?

### ISSUE THREAD

**Issue by cherryjm** [fabbrimatteo/LoCO#2]
Hi! Thank you for your great work!
It seems that only training code for code predictor is provided. Could you please release training code for VHA? Many thanks!

**Comment by fabbrimatteo** [comment]
Yes, I'll provide the code as soon as I can, along with the code for Human3.6m and Panoptic. Stay tuned!

**Comment by fabbrimatteo** [comment]
I added a link to the code for training the autoencoder. Feel free to report any bugs!
