### ISSUE TITLE
Compile Cuda Kernel

### ISSUE THREAD

**Issue by ZXin0305** [fabbrimatteo/LoCO#21]
How to do the task??
I couldn't find the answer you told me last time...Sorry,it seems a waste of your time to tell me again.

**Comment by fabbrimatteo** [comment]
Hi,
Please, follow those instructions:
- `cd` into the folder `nms3d` and run `python setup.py install` (python >= 3.6). Make sure to add your cuda directory to your environment variables.

**Comment by ZXin0305** [comment]
ok!Thank you very much!!!  I have made it come true.But there is another problem that I try to run the demo of yours while the result is seems not good. The method I run the demo.py is to take a single image of CMU dataset as input  with changing the camera parameters ,but the keyoints num is wrong and the position always appears in the four corners of the picture.The same can happen if the original method is used.

**Comment by fabbrimatteo** [comment]
Hi,
You cannot use JTA pre-trained weights for CMU Panoptic. You have to re-train the pipeline for that. For the demo.py you can only use JTA images.

**Comment by ZXin0305** [comment]
ok!But I could't get the dataset because I couldn't send the Emaill ...Could you give me a key of the dataset? I hope I can use this data as soon as possible. Thank you again.

**Comment by fabbrimatteo** [comment]
Please, to request the JTA dataset, follow the instructions reported [here](https://github.com/fabbrimatteo/JTA-Dataset#obtain-the-dataset)

**Comment by ZXin0305** [comment]
ok.Is the Email address right? "matteo_DOT_fabbri_AT_unimore_DOT_it <>".I use gmail but I could't send the email and said that the email address is not in the right format

**Comment by fabbrimatteo** [comment]
https://github.com/fabbrimatteo/JTA-Dataset/issues/3#issuecomment-437082916

**Comment by ZXin0305** [comment]
Thank you!I have sent the email yesterday.
