### ISSUE TITLE
something about the model

### ISSUE THREAD

**Issue by ZXin0305** [fabbrimatteo/LoCO#25]
I know that always asking you some irrelevant questions may waste your time, but I really hope to be able to reproduce your results on my own computer.
I have followed the steps to retrain the code-predcitor part, but the f1-score　 is not particularly high during the test. I tried to use your pre-trained model and my own retrained VHA model. The effect was not as good as I expected. Due to the limited storage capacity, I only extracted some video frames and made a "bottleneck code" for code-predictor training. Will this cause the training model to be inaccurate? At present, I can't think of any other way besides tuning parameters...
Thank you very very very very much !!!

**Comment by fabbrimatteo** [comment]
If you want to reproduce the paper results you should use the whole JTA dataset. Maybe try to use one every 10 or every 50 frames of the whole dataset.

**Comment by ZXin0305** [comment]
Thank you , I would try it again.
