### ISSUE TITLE
Issue with the precomputed code zip file

### ISSUE THREAD

**Issue by shubhajitbasak** [fabbrimatteo/LoCO#28]
Thanks for your work and for releasing the code.
I am trying to download the precomputed codes from the following link -
https://ailb-web.ing.unimore.it/publicfiles/drive/CVPR%202020%20-%20LoCO/codes.zip
But it seems the zip file is corrupted and unable to extract from it. Request you to please check.

**Comment by fabbrimatteo** [comment]
Can you try again now?

**Comment by sk-zhang** [comment]
@fabbrimatteo  Hi, I just downloaded the pretrained weights and have the same problem! It seems the zip file is corrupted and unable to extract from it.

**Comment by fabbrimatteo** [comment]
If you are on Windows, try using 7zip (https://www.7-zip.org/)

**Comment by sk-zhang** [comment]
@fabbrimatteo Thanks for your reply, I used 7-zip but still can't unzip successfully!
![微信截图_20230928152429](https://github.com/fabbrimatteo/LoCO/assets/65368867/fd5fa1b5-594d-404d-bc52-8f9c72484efe)

**Comment by fabbrimatteo** [comment]
Try again now. Not sure if weights are correct btw. Please test them

**Comment by sk-zhang** [comment]
Sorry for getting back to you so late. I tested the weights and realized that the weights don't match the model right now.
![微信截图_20231008210036](https://github.com/fabbrimatteo/LoCO/assets/65368867/722d1e09-702d-4be0-8c74-a141a9c65460)

**Comment by fabbrimatteo** [comment]
That's unfortunate. I think I might have lost the weights then. Sorry for that

**Comment by sk-zhang** [comment]
Okay, thanks for your help anyway.

**Comment by sk-zhang** [comment]
@fabbrimatteo Sorry to bother you again! The weights were not available so I tried to retrain the model. But as with that issue, the zip code is corrupted, I wonder if you still have the full zip? Is the zip necessary?

**Comment by fabbrimatteo** [comment]
Try with [this](https://drive.google.com/file/d/137miqC9A8RO1VWxv7J_j7firx7m57Exw/view?usp=sharing). It contains the best model and the .ck checkpoint file

**Comment by sk-zhang** [comment]
Unfortunately, when I follow the steps below, it still reports an error, is this a problem with my environment or the weights?
![image](https://github.com/fabbrimatteo/LoCO/assets/65368867/7f331e03-2804-4c7a-8ea7-355373335891)
![image](https://github.com/fabbrimatteo/LoCO/assets/65368867/541da76e-d0df-457e-bdeb-ebfd38ea161a)
Also, do you still have the zip package marked below? The current one seems to be corrupted.
![image](https://github.com/fabbrimatteo/LoCO/assets/65368867/1352ce90-26ee-4b64-b75d-7b4a860ed3f7)

**Comment by fabbrimatteo** [comment]
Well, it seems like every zip file is corrupted. This is probably due to the abrupt interruption of electric power that happened months ago to our servers. Looks like those files were in the 0.06% of the total corrupted files. Unfortunately I have to remove the download links. About the weights you are trying to use, those probably come from an older version of our method. Sorry for the inconvenience

**Comment by fabbrimatteo** [comment]
Ok last chance. Try this [best](https://drive.google.com/file/d/1sRAUB6EhzC0sypjcbX8gv6FwpVg21k1i/view?usp=share_link) model. If it does not work, please try using this [code_predictor](https://drive.google.com/file/d/1iCCx16-B_KVHjfAoK8gl5wxwn4IBsL9N/view?usp=share_link) model instead.

**Comment by sk-zhang** [comment]
Thank you very much, it works now! But there's still a problem when displaying the result graph, it doesn't show anything.
![微信截图_20231023143721](https://github.com/fabbrimatteo/LoCO/assets/65368867/7f64b11a-cff9-4896-b78e-ec7e712fa915)
I debugged the program and found that the predicted pseudo-3D coordinates are empty set. Do you know why this is?

**Comment by fabbrimatteo** [comment]
If you take the max of the volumetric heatmaps is still zero? Try replacing the autoencoder weights with [those](https://drive.google.com/file/d/1Yg0H7qQmrwPOGceUSK9QQoZnhI7uyB1K/view?usp=share_link).

**Comment by sk-zhang** [comment]
First of all, thank you very much for your patience. I'm a beginner in this field, and there are many things I don't understand. I appreciate your guidance.

The maximum value of the volumetric heat map is not zero, though it looks like it's a bit small. And all are eliminated later in the nms_th judgment.
![image](https://github.com/fabbrimatteo/LoCO/assets/65368867/c32eb4af-8336-4eca-8b75-aadbc209b7e0)
Here are the hyperparameters in the pretrained file, I only changed JTA_PATH as per the readme.md file.
`# pretrained
Q: 0.31746031746031744
LR: 0.0001
EPOCHS: 999
DET_TH: 0.4
NMS_TH: 0.1
N_WORKERS: 8
BATCH_SIZE: 1
DEVICE: 'cuda:0'
EPOCH_LEN: 4096
TEST_SET_LEN: 128
JTA_PATH: 'E:\datasets\JTA-Dataset'`

I tried the new vha.pth you provided, but it doesn't seem to have changed anything.

**Comment by fabbrimatteo** [comment]
No worries :) 
Are you using images from JTA?

**Comment by sk-zhang** [comment]
Yes, I followed the instructions, but I don't have the precomputed codes. The following runtime message indicates that loading the image should be correct.
![image](https://github.com/fabbrimatteo/LoCO/assets/65368867/4bd78118-5b44-4cea-8a48-6bda09228ee8)

**Comment by fabbrimatteo** [comment]
Could you try using an image from the CMU Panoptic Dataset? Maybe the weights I shared come from the Panoptic training.

**Comment by sk-zhang** [comment]
OK. However, I don't have the CMU Panoptic Dataset right now, and it's not easy for me to download the dataset. I'll try to test it afterward, but it might take some time.

**Comment by sk-zhang** [comment]
Sorry for getting back to you so late. For some specific reason I couldn't go and validate the idea above. But I was initially trying to use the JTA dataset, which has now been resolved. Thank you for your patience in replying and thank you very much for the JTA dataset, I wish you a happy and successful day.

**Comment by fabbrimatteo** [comment]
Thank you :) appreciated. Good luck!
