### ISSUE TITLE
Association Algorithm

### ISSUE THREAD

**Issue by yangsenius** [fabbrimatteo/LoCO#3]
Thanks for your awesome work!

The code in the `coords_to_poses` function looks like a greedy heuristic association algorithm. But I note that the supplementary material in the paper describes that the skeleton grouping uses the Hungarian algorithm with cost matrix. Is the mentioned Hungarian algorithm not included in the current code or just the `coords_to_poses` function?

**Comment by fabbrimatteo** [comment]
Hi @yangsenius,

Thanks for your interest in our work! You are right. This version of the code is not the latest one. I am really sorry but I was pretty busy lately. We will fix the code before the CVPR conference (a couple of weeks) by adding everything including the autoencoder training. Stay tuned!

**Comment by yangsenius** [comment]
Hi, @fabbrimatteo.
 
Waiting for the new version. Wish you all the best!
