### ISSUE TITLE
how does the to3d func work?

### ISSUE THREAD

**Issue by longbowzhang** [fabbrimatteo/LoCO#4]
Hi, thanks for sharing the great work.
I have a question about heatmap. I noticed that you encode the distance of the joints to the camera `cam_dist = np.sqrt(joint.x3d ** 2 + joint.y3d ** 2 + joint.z3d ** 2)` , why not simply encode the z-depth value of the joints `joint.z3d`? any particular reason?

Besides, could you elaborate a little bit on  https://github.com/fabbrimatteo/LoCO/blob/7ebaca7eec4ff3d6fb4b892c5aacb47e2b3469b9/utils.py#L97, basically what does this k value mean?https://github.com/fabbrimatteo/LoCO/blob/8371ef0f4622c58667307cdf444cad0c2b17be16/utils.py#L113

**Comment by fabbrimatteo** [comment]
Hi @longbowzhang,

Thank you for your interest in our work. 

You are right, it is much simpler to encode the z-depth value directly. In fact we used this approach for Panoptic and Human3.6 as described in the paper's supplementary material.

As for the to3d function, it has been obtained by solving the following system w.r.t. the 3D coordinates:

<a href="https://www.codecogs.com/eqnedit.php?latex=\large&space;\left\{\begin{matrix}&space;x_\textup{2D}&space;&&space;=&space;f_{x}&space;\cdot&space;\frac{x_\textup{3D}}{z_\textup{3D}}&space;&plus;&space;c_{x}&space;\\&space;y_\textup{2D}&space;&&space;=&space;f_{y}&space;\cdot&space;\frac{y_\textup{3D}}{z_\textup{3D}}&space;&plus;&space;c_{y}&space;\\&space;d&space;&&space;=&space;\sqrt{x_\textup{3D}^2&space;&plus;&space;y_\textup{3D}^2&space;&plus;&space;z_\textup{3D}^2}&space;\end{matrix}\right." target="_blank"><img src="https://latex.codecogs.com/png.latex?\large&space;\left\{\begin{matrix}&space;x_\textup{2D}&space;&&space;=&space;f_{x}&space;\cdot&space;\frac{x_\textup{3D}}{z_\textup{3D}}&space;&plus;&space;c_{x}&space;\\&space;y_\textup{2D}&space;&&space;=&space;f_{y}&space;\cdot&space;\frac{y_\textup{3D}}{z_\textup{3D}}&space;&plus;&space;c_{y}&space;\\&space;d&space;&&space;=&space;\sqrt{x_\textup{3D}^2&space;&plus;&space;y_\textup{3D}^2&space;&plus;&space;z_\textup{3D}^2}&space;\end{matrix}\right." title="\large \left\{\begin{matrix} x_\textup{2D} & = f_{x} \cdot \frac{x_\textup{3D}}{z_\textup{3D}} + c_{x} \\ y_\textup{2D} & = f_{y} \cdot \frac{y_\textup{3D}}{z_\textup{3D}} + c_{y} \\ d & = \sqrt{x_\textup{3D}^2 + y_\textup{3D}^2 + z_\textup{3D}^2} \end{matrix}\right." /></a>

k is just a recurrent coefficient calculated one time and used to obtain each 3D coordinate.
