### ISSUE TITLE
some pro while train

### ISSUE THREAD

**Issue by haolianyi** [fabbrimatteo/LoCO#5]
Thanks for your amazing work!
  I meet a problem when I run train as your instruction by using codes you provided,
  It likes that:
  FileNotFoundError : [ Error 2] No such file or directory: Path / LoCO /codes/poses/val')  LoCO is my project path
  Maybe is the data problem or what, looking forward to hearing from you

**Comment by fabbrimatteo** [comment]
Hi @haolianyi,

Did you follow the instructions in the README and run `python to_poses.py --out_dir_path='poses' --format='torch'`? Have you modified the file `conf/default.yaml` specifying your JTA path?
