### ISSUE TITLE
Training samples

### ISSUE THREAD

**Issue by yangsenius** [fabbrimatteo/LoCO#6]
How many samples of CMU panoptic dataset are used for training?

The paper mentions that the experiments about CMU Panoptic follow the test protocol defined in *Monocular 3d pose and shape estimation of multiple people in natural scenes*.  

I read that paper but it only describes the setup for testing. Does it means all of samples (downloaded by [panoptic-toolbox](https://github.com/CMU-Perceptual-Computing-Lab/panoptic-toolbox)) except those hold out from *Haggling, Mafia, Ultimatum and Pizza* of CMU panoptic are taken as training samples?

**Comment by fabbrimatteo** [comment]
Exactly, we used all the samples except those used for testing.
