### ISSUE TITLE
How did you do the eval ?

### ISSUE THREAD

**Issue by marsalr** [fabbrimatteo/LoCO#7]
Hello,

Thanks for your amazing work !

I am trying to obtain the same results as you did on the paper so I used the test function in trainer.py but my recall is always lower. How did you do the eval ? Did you use the same parameters in the eval as in pretrained.yaml ? 
Can you add you eval code on github ?

**Comment by YangJae96** [comment]
How did you run the  "show.py" script??
![image](https://user-images.githubusercontent.com/57695621/90500653-26bcdc00-e186-11ea-8349-a5704a35772c.png)

I can not run the script because there is no 
dataset.test_set script..
How did you solve it??
Can you please help me.

**Comment by WManYang** [comment]
Hi, 
thank you for your great work!

I have some problem to ask you.

for training the "code_predictor" model,   the labeled data "y_true" is firstly  obtained by "autoencoder.encode()" ??

moreover, I do not see where did you train the autoencoder.

thank you very much.

**Comment by fabbrimatteo** [comment]
Hi @remimar, 
sorry for the huge delay in my response. I added the `eval.py` script. Let me know if you can reproduce the results of the paper.

**Comment by fabbrimatteo** [comment]
Hi @YangJae96, I fixed the issue. Now you should be able to run the script.

**Comment by fabbrimatteo** [comment]
Hi @WManYang, 
Yes, you are right: `y_true` is obtained using the autoencoder's encode function. As stated in the README, you can find the training code for the autoencoder [here](https://github.com/fabbrimatteo/VHA).

**Comment by cvNXE** [comment]
Hello, thank you very much for sharing your research . May I ask you a question? I want to use pre-trained LoCo to estimate the 
 human pose of other databases. Do I have to provide the camera  intrinsic parameters related to this database for LoCo?  What if I can't provide the camera  intrinsic parameters？

**Comment by fabbrimatteo** [comment]
If you want to obtain reliable predictions, you should utilize only images that have been obtained with the same intrinsic parameters used during training. 
If you want to use images obtained with different intrinsic parameters (and you know the parameters) simply replacing them in the functions will not work. But probably there is a way to move from two camera spaces knowing the intrinsic parameters of the two spaces. If you find the solution can you please post it here? :)
If you feed the network with images with unknown parameters you will have unpredictable results. In this scenario, keep the same parameters used during training. 3D coords will be not reliable, but the order will be fine (they will look stretched).
