### ISSUE TITLE
My image model inference?

### ISSUE THREAD

**Issue by YangJae96** [fabbrimatteo/LoCO#8]
Hello. I ran the demo code and figured out that it only visualizes
the already estimated 2D poses and 3D Poses.

Is there a way to input my own image to the model 
and then visualize the 2D image results and 3D Poses  which uses mlab(In the Demo.py).??
How can I obtain the 3D pose data just like "1_res.data" in the demo dir.

Thanks in advance.

**Comment by Frank-Dz** [comment]
> Hello. I ran the demo code and figured out that it only visualizes
> the already estimated 2D poses and 3D Poses.
> 
> Is there a way to input my own image to the model
> and then visualize the 2D image results and 3D Poses which uses mlab(In the Demo.py).??
> How can I obtain the 3D pose data just like "1_res.data" in the demo dir.
> 
> Thanks in advance.

Did you solve the problem?

**Comment by fabbrimatteo** [comment]
If you want to use your own images you can modify the `show.py` script at your convenience.
